# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\Tests\Password vault\Vault_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 768)
        self.MasterPassword_input = PasswordLineEdit(Form)
        self.MasterPassword_input.setGeometry(QtCore.QRect(10, 20, 791, 33))
        self.MasterPassword_input.setObjectName("MasterPassword_input")
        self.MainTable = TableWidget(Form)
        self.MainTable.setGeometry(QtCore.QRect(10, 70, 791, 391))
        self.MainTable.setObjectName("MainTable")
        self.MainTable.setColumnCount(3)
        self.MainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(2, item)
        self.FetchPasswords_Button = PrimaryPushButton(Form)
        self.FetchPasswords_Button.setGeometry(QtCore.QRect(10, 490, 791, 32))
        self.FetchPasswords_Button.setObjectName("FetchPasswords_Button")
        self.output_TextEdit = TextEdit(Form)
        self.output_TextEdit.setGeometry(QtCore.QRect(10, 540, 791, 181))
        self.output_TextEdit.setObjectName("output_TextEdit")
        self.Flush_TextEdit = PushButton(Form)
        self.Flush_TextEdit.setGeometry(QtCore.QRect(700, 730, 102, 32))
        self.Flush_TextEdit.setObjectName("Flush_TextEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.MainTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Machine name"))
        self.MainTable.setColumnWidth(0,400) 
        item = self.MainTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "IP address"))
        self.MainTable.setColumnWidth(1,280) 
        item = self.MainTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Action"))
        self.MainTable.setColumnWidth(2,95) 
        self.FetchPasswords_Button.setText(_translate("Form", "Fetch passwords"))
        self.Flush_TextEdit.setText(_translate("Form", "Flush"))
from qfluentwidgets import PasswordLineEdit, PrimaryPushButton, PushButton, TableWidget, TextEdit
