# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\FinishedProduct\MainInterface\Remove_machines\RemoveMachinesInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 768)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 811, 761))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.MainTable = TableWidget(self.gridLayoutWidget)
        self.MainTable.setObjectName("MainTable")
        self.MainTable.setColumnCount(3)
        self.MainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.MainTable, 0, 0, 1, 1)
        self.RemoveMachinesButton = PrimaryPushButton(self.gridLayoutWidget)
        self.RemoveMachinesButton.setObjectName("RemoveMachinesButton")
        self.gridLayout.addWidget(self.RemoveMachinesButton, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.MainTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Machine Name"))
        item = self.MainTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "IP address"))
        item = self.MainTable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Action"))
        self.RemoveMachinesButton.setText(_translate("Form", "Remove selected machines"))
from qfluentwidgets import PrimaryPushButton, TableWidget
