# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\Tests\File transfer\Fetch_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(579, 768)
        self.MainTable = TableWidget(Frame)
        self.MainTable.setGeometry(QtCore.QRect(9, 210, 785,580))
        self.MainTable.setObjectName("MainTable")
        self.MainTable.setColumnCount(3)
        self.MainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(2, item)
        self.Fetch_button = PrimaryPushButton(Frame)
        self.Fetch_button.setGeometry(QtCore.QRect(635, 800, 161, 32))
        self.Fetch_button.setObjectName("Fetch_button")
        self.Localpath = LineEdit(Frame)
        self.Localpath.setGeometry(QtCore.QRect(9, 50, 650, 33))
        self.Localpath.setObjectName("Localpath")
        self.Browse = PushButton(Frame)
        self.Browse.setGeometry(QtCore.QRect(675, 50, 121, 32))
        self.Browse.setObjectName("Browse")
        self.Title1 = StrongBodyLabel(Frame)
        self.Title1.setGeometry(QtCore.QRect(9, 20, 131, 19))
        self.Title1.setObjectName("Title1")
        self.LineEdit = LineEdit(Frame)
        self.LineEdit.setGeometry(QtCore.QRect(9, 100, 650, 33))
        self.LineEdit.setObjectName("LineEdit")
        self.PushButton = PushButton(Frame)
        self.PushButton.setGeometry(QtCore.QRect(675, 100, 121, 32))
        self.PushButton.setObjectName("PushButton")
        self.StrongBodyLabel = StrongBodyLabel(Frame)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(10, 190, 111, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.Master_password=QtWidgets.QLineEdit(parent=Frame)
        self.Master_password.setGeometry(QtCore.QRect(10, 150, 650, 27))
        self.Master_password.setObjectName("Master_password")
        self.Master_password.setEchoMode(QtWidgets.QLineEdit.Password)  #pour  masquer le mot de passe lors de lecriture avec des points


        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Form"))
        item = self.MainTable.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "Machine Name"))
        self.MainTable.setColumnWidth(0,200) 
        item = self.MainTable.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "IP Address"))
        self.MainTable.setColumnWidth(1,250) 
        item = self.MainTable.horizontalHeaderItem(2)
        
        item.setText(_translate("Frame", "Select"))
        
        self.Fetch_button.setText(_translate("Frame", "Fetch"))
        self.Localpath.setPlaceholderText(_translate("Frame", "Local path (select the destination folder)"))
        self.Browse.setText(_translate("Frame", "Browse"))
        self.Title1.setText(_translate("Frame", "Fetch a file/folder:"))
        self.LineEdit.setPlaceholderText(_translate("Frame", "Remote path"))
        self.PushButton.setText(_translate("Frame", "Verify existance"))
        self.StrongBodyLabel.setText(_translate("Frame", "Machines online:"))
        self.Master_password.setPlaceholderText(_translate("Frame", "Master Password"))
from qfluentwidgets import LineEdit, PrimaryPushButton, PushButton, StrongBodyLabel, TableWidget




