# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\Tests\log_fetcher_interface\logfetcher_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 768)
        self.TreeWidget = TreeWidget(Form)
        self.TreeWidget.setGeometry(QtCore.QRect(20, 60, 771, 651))
        self.TreeWidget.setObjectName("TreeWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TreeWidget.headerItem().setText(0, _translate("Form", "Machine name"))
        self.TreeWidget.setColumnWidth(0, 250)
        self.TreeWidget.headerItem().setText(1, _translate("Form", "IP"))
        self.TreeWidget.setColumnWidth(1, 150)
        self.TreeWidget.headerItem().setText(2, _translate("Form", "Status"))
        self.TreeWidget.setColumnWidth(2, 100)
        self.TreeWidget.headerItem().setText(3, _translate("Form", "Latest fetch"))
        self.TreeWidget.setColumnWidth(3, 150)
        self.TreeWidget.headerItem().setText(4, _translate("Form", "Actions"))
from qfluentwidgets import TreeWidget
