# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\Tests\Traps viewer\Traps_Viewer_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(813, 768)
        self.All_Traps_received = TextEdit(Form)
        self.All_Traps_received.setGeometry(QtCore.QRect(10, 50, 791, 711))
        self.All_Traps_received.setReadOnly(True)
        self.All_Traps_received.setObjectName("All_Traps_received")
        self.Filter = SearchLineEdit(Form)
        self.Filter.setGeometry(QtCore.QRect(10, 10, 691, 33))
        self.Filter.setText("")
        self.Filter.setPlaceholderText("")
        self.Filter.setObjectName("Filter")
        self.Filter_Button = PrimaryPushButton(Form)
        self.Filter_Button.setGeometry(QtCore.QRect(710, 10, 91, 32))
        self.Filter_Button.setObjectName("Filter_Button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Filter_Button.setText(_translate("Form", "Filter"))
from qfluentwidgets import PrimaryPushButton, SearchLineEdit, TextEdit
