# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\Tests\adding_machines\Config_progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form3(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(474, 459)
        self.configprogress_TextEdit = TextEdit(Form)
        self.configprogress_TextEdit.setGeometry(QtCore.QRect(10, 10, 451, 381))
        self.configprogress_TextEdit.setObjectName("configprogress_TextEdit")
        self.configprogress_finish = PrimaryPushButton(Form)
        self.configprogress_finish.setGeometry(QtCore.QRect(330, 400, 131, 51))
        self.configprogress_finish.setObjectName("configprogress_finish")
        self.Loading = StateToolTip(title='Please Wait', content='Configuration is running', parent=Form)
        self.Loading.setEnabled(True)
        self.Loading.setGeometry(QtCore.QRect(10, 400, 256, 51))
        self.Loading.setObjectName("Loading")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.configprogress_finish.setText(_translate("Form", "Finish"))
from qfluentwidgets import PrimaryPushButton, StateToolTip, TextEdit
