# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\Tests\SSH_Widget\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(579, 768)
        self.MainTable = TableWidget(Frame)
        self.MainTable.setGeometry(QtCore.QRect(10, 50, 561, 491))
        self.MainTable.setObjectName("MainTable")
        self.MainTable.setColumnCount(3)
        self.MainTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.MainTable.setHorizontalHeaderItem(2, item)
        self.OpenMultiSSH = PrimaryPushButton(Frame)
        self.OpenMultiSSH.setGeometry(QtCore.QRect(950, 550, 191, 40))
        self.OpenMultiSSH.setObjectName("OpenMultiSSH")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        item = self.MainTable.horizontalHeaderItem(0)
        self.MainTable.setColumnWidth(0,150) 
        
        item.setText(_translate("Frame", "Machine Name"))
        item = self.MainTable.horizontalHeaderItem(1)
        self.MainTable.setColumnWidth(1,190) 
        
        item.setText(_translate("Frame", "IP Address"))
        item = self.MainTable.horizontalHeaderItem(2)
        self.MainTable.setColumnWidth(2,200) 
        
        item.setText(_translate("Frame", "Actions"))
        self.OpenMultiSSH.setText(_translate("Frame", "Open Multi-SSH window"))
from qfluentwidgets import PrimaryPushButton, TableWidget
