#!/bin/bash
#turn into an executable with: chmod +x setup.sh
#run as root

echo "Installing net-snmp RPMs..."
yum install -y net-snmp net-snmp-libs net-snmp-utils net-snmp-agent-libs

rm -rf  /etc/snmp/snmpd.conf
touch /etc/snmp/snmpd.conf

systemctl stop snmpd

echo "Setting up..."
echo "com2sec notConfigUser  default       teststring" >> /etc/snmp/snmpd.conf
echo "group   notConfigGroup v1           notConfigUser" >> /etc/snmp/snmpd.conf
echo "group   notConfigGroup v2c           notConfigUser" >> /etc/snmp/snmpd.conf
echo "view    systemview    included   .1.3.6.1.2.1.1" >> /etc/snmp/snmpd.conf
echo "view    systemview    included   .1.3.6.1.2.1.25.1.1" >> /etc/snmp/snmpd.conf
echo "access  notConfigGroup \"\"      any       noauth    exact  systemview none none" >> /etc/snmp/snmpd.conf
echo "syslocation " >> /etc/snmp/snmpd.conf #can be removed
echo "syscontact " >> /etc/snmp/snmpd.conf
echo "dontLogTCPWrappersConnects yes" >> /etc/snmp/snmpd.conf
echo "createUser roadmin SHA admin123 AES admin123" >> /etc/snmp/snmpd.conf
echo "rouser roadmin authpriv system" >> /etc/snmp/snmpd.conf
echo "informsink 192.168.69.45 teststring" >> /etc/snmp/snmpd.conf
echo "authtrapenable 2" >> /etc/snmp/snmpd.conf
echo "agentSecName roadmin" >> /etc/snmp/snmpd.conf
echo "defaultMonitors yes" >> /etc/snmp/snmpd.conf

#username stays the same, password must be changed, community string must be entered by the user, this file needs to be generated by a python script

echo "Enabling and starting snmpd service..."
systemctl enable snmpd
systemctl start snmpd
systemctl restart snmpd

echo "Setting up the firewall..."
firewall-cmd --add-service=snmp --permanent
firewall-cmd --zone=public --add-port=161/udp --permanent
firewall-cmd --zone=public --add-port=162/udp --permanent
firewall-cmd --reload


echo "SNMP configuration completed."

Below is the /etc/snmp/snmpd.conf file with snmp v1 and v2 disabled

 view    systemview    included   .1.3.6.1.2.1.1
 view    systemview    included   .1.3.6.1.2.1.25.1.1
 view all    included  .1                               80
 view mib2   included  .iso.org.dod.internet.mgmt.mib-2 fc
 syslocation Unknown 
 syscontact Root 
 createUser roadmin SHA admin123 AES admin123
 rouser roadmin authpriv system