# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\BALLS2 (rip BALLS)\Desktop\REMT\FinishedProduct\MasterPasswordInput\FirstLoginInterface\FirstLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 426)
        self.StrongBodyLabel = StrongBodyLabel(Form)
        self.StrongBodyLabel.setGeometry(QtCore.QRect(10, 180, 171, 19))
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.BodyLabel_2 = BodyLabel(Form)
        self.BodyLabel_2.setGeometry(QtCore.QRect(10, 220, 671, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.BodyLabel = BodyLabel(Form)
        self.BodyLabel.setGeometry(QtCore.QRect(10, 200, 1061, 19))
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 572, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PasswordInput = PasswordLineEdit(self.verticalLayoutWidget)
        self.PasswordInput.setObjectName("PasswordInput")
        self.verticalLayout.addWidget(self.PasswordInput)
        self.PasswordInput2 = PasswordLineEdit(self.verticalLayoutWidget)
        self.PasswordInput2.setObjectName("PasswordInput2")
        self.verticalLayout.addWidget(self.PasswordInput2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.CloseMasterPWDWindow = PushButton(self.verticalLayoutWidget)
        self.CloseMasterPWDWindow.setObjectName("CloseMasterPWDWindow")
        self.horizontalLayout.addWidget(self.CloseMasterPWDWindow)
        self.MasterPWDContinue = PrimaryPushButton(self.verticalLayoutWidget)
        self.MasterPWDContinue.setMinimumSize(QtCore.QSize(150, 0))
        self.MasterPWDContinue.setObjectName("MasterPWDContinue")
        self.horizontalLayout.addWidget(self.MasterPWDContinue)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 571, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.TitleLabel = TitleLabel(self.verticalLayoutWidget_2)
        self.TitleLabel.setObjectName("TitleLabel")
        self.horizontalLayout_2.addWidget(self.TitleLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.RemtLogo = QtWidgets.QLabel(Form)
        self.RemtLogo.setGeometry(QtCore.QRect(230, 70, 121, 131))
        self.RemtLogo.setStyleSheet("label {\n"
"    opacity: 0.25;\n"
"}\n"
"")
        self.RemtLogo.setText("")
        self.RemtLogo.setPixmap(QtGui.QPixmap("../REMT/FinishedProduct/MasterPasswordInput/FirstLoginInterface/black.png"))

        self.RemtLogo.setScaledContents(True)
        self.RemtLogo.setObjectName("RemtLogo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.StrongBodyLabel.setText(_translate("Form", "Enter a master Password"))
        self.BodyLabel_2.setText(_translate("Form", "and the key for encrypting and decrypting passwords."))
        self.BodyLabel.setText(_translate("Form", "Please note that the password you\'re about to select will enter as both your login credentials "))
        self.PasswordInput.setPlaceholderText(_translate("Form", "Master Password"))
        self.PasswordInput2.setPlaceholderText(_translate("Form", "Re-enter the Master Password"))
        self.CloseMasterPWDWindow.setText(_translate("Form", "Cancel"))
        self.MasterPWDContinue.setText(_translate("Form", "Save"))
        self.TitleLabel.setText(_translate("Form", "Welcome To REMT !"))
from qfluentwidgets import BodyLabel, PasswordLineEdit, PrimaryPushButton, PushButton, StrongBodyLabel, TitleLabel
